/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'productType' : ProductType,
  'imageUrl' : string,
  'price' : bigint,
  'isTrending' : boolean,
}
export type ProductId = string;
export type ProductType = { 'pendulum' : null } |
  { 'bracelet' : null } |
  { 'crystal' : null };
export interface Service {
  'id' : ServiceId,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type ServiceId = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [ProductId, string, string, string, ProductType, boolean],
    undefined
  >,
  'addService' : ActorMethod<[string, string, bigint], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteService' : ActorMethod<[ServiceId], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[ProductType], Array<Product>>,
  'getProductsByType' : ActorMethod<[ProductType], Array<Product>>,
  'getService' : ActorMethod<[ServiceId], Service>,
  'getTrendingProducts' : ActorMethod<[], Array<Product>>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, string, ProductType, bigint, boolean],
    undefined
  >,
  'updateService' : ActorMethod<[ServiceId, string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];