/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const ProductType = IDL.Variant({
  'pendulum' : IDL.Null,
  'bracelet' : IDL.Null,
  'crystal' : IDL.Null,
});
export const ServiceId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productType' : ProductType,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
  'isTrending' : IDL.Bool,
});
export const Service = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Text, ProductType, IDL.Bool],
      [],
      [],
    ),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteService' : IDL.Func([ServiceId], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductType],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByType' : IDL.Func([ProductType], [IDL.Vec(Product)], ['query']),
  'getService' : IDL.Func([ServiceId], [Service], ['query']),
  'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Text, ProductType, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateService' : IDL.Func([ServiceId, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const ProductType = IDL.Variant({
    'pendulum' : IDL.Null,
    'bracelet' : IDL.Null,
    'crystal' : IDL.Null,
  });
  const ServiceId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productType' : ProductType,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  const Service = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Text, ProductType, IDL.Bool],
        [],
        [],
      ),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteService' : IDL.Func([ServiceId], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductType],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByType' : IDL.Func(
        [ProductType],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getService' : IDL.Func([ServiceId], [Service], ['query']),
    'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ProductType,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateService' : IDL.Func(
        [ServiceId, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };