/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TarotService {
    id: bigint;
    isUrgent: boolean;
    name: string;
    description: string;
    category: ServiceCategory;
    price: bigint;
    isVoiceNote: boolean;
}
export type ProductId = string;
export interface Appointment {
    status: string;
    dateOfBirth: string;
    createdAt: bigint;
    selectedServicePrice: bigint;
    fullName: string;
    email: string;
    selectedService: string;
    problemDescription: string;
    phone: string;
}
export interface Product {
    id: ProductId;
    name: string;
    description: string;
    productType: ProductType;
    imageUrl: string;
    price: bigint;
    isTrending: boolean;
}
export interface UserProfile {
    name: string;
}
export enum ProductType {
    pendulum = "pendulum",
    bracelet = "bracelet",
    crystal = "crystal"
}
export enum ServiceCategory {
    careerMoneyLife = "careerMoneyLife",
    premiumExclusive = "premiumExclusive",
    miniReading = "miniReading",
    deepDetailed = "deepDetailed",
    loveRelationship = "loveRelationship"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(id: ProductId, name: string, description: string, imageUrl: string, productType: ProductType, isTrending: boolean): Promise<void>;
    addTarotService(name: string, description: string, price: bigint, category: ServiceCategory, isVoiceNote: boolean, isUrgent: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAppointment(fullName: string, dateOfBirth: string, phone: string, email: string, problemDescription: string, selectedService: string, selectedServicePrice: bigint): Promise<void>;
    deleteProduct(id: ProductId): Promise<void>;
    deleteTarotService(id: bigint): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getAllTarotServices(): Promise<Array<TarotService>>;
    getAppointments(): Promise<Array<Appointment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProduct(id: ProductId): Promise<Product>;
    getProductsByCategory(category: ProductType): Promise<Array<Product>>;
    getProductsByType(productType: ProductType): Promise<Array<Product>>;
    getTarotService(id: bigint): Promise<TarotService>;
    getTarotServiceCatalog(): Promise<{
        careerMoneyLife: Array<TarotService>;
        premiumExclusive: Array<TarotService>;
        miniReadings: Array<TarotService>;
        deepDetailed: Array<TarotService>;
        loveRelationship: Array<TarotService>;
    }>;
    getTarotServicesByCategory(category: ServiceCategory): Promise<Array<TarotService>>;
    getTrendingProducts(): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateProduct(id: ProductId, name: string, description: string, imageUrl: string, productType: ProductType, price: bigint, isTrending: boolean): Promise<void>;
    updateTarotService(id: bigint, name: string, description: string, price: bigint, category: ServiceCategory, isVoiceNote: boolean, isUrgent: boolean): Promise<void>;
}
import type { Product as _Product, ProductId as _ProductId, ProductType as _ProductType, ServiceCategory as _ServiceCategory, TarotService as _TarotService, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: ProductId, arg1: string, arg2: string, arg3: string, arg4: ProductType, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, to_candid_ProductType_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, to_candid_ProductType_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async addTarotService(arg0: string, arg1: string, arg2: bigint, arg3: ServiceCategory, arg4: boolean, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTarotService(arg0, arg1, arg2, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTarotService(arg0, arg1, arg2, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteTarotService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTarotService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTarotService(arg0);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTarotServices(): Promise<Array<TarotService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTarotServices();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTarotServices();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: ProductType): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ProductType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ProductType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByType(arg0: ProductType): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByType(to_candid_ProductType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByType(to_candid_ProductType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTarotService(arg0: bigint): Promise<TarotService> {
        if (this.processError) {
            try {
                const result = await this.actor.getTarotService(arg0);
                return from_candid_TarotService_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTarotService(arg0);
            return from_candid_TarotService_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTarotServiceCatalog(): Promise<{
        careerMoneyLife: Array<TarotService>;
        premiumExclusive: Array<TarotService>;
        miniReadings: Array<TarotService>;
        deepDetailed: Array<TarotService>;
        loveRelationship: Array<TarotService>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTarotServiceCatalog();
                return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTarotServiceCatalog();
            return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTarotServicesByCategory(arg0: ServiceCategory): Promise<Array<TarotService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTarotServicesByCategory(to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTarotServicesByCategory(to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingProducts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingProducts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: string, arg2: string, arg3: string, arg4: ProductType, arg5: bigint, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, to_candid_ProductType_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, to_candid_ProductType_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async updateTarotService(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: ServiceCategory, arg5: boolean, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTarotService(arg0, arg1, arg2, arg3, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTarotService(arg0, arg1, arg2, arg3, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
}
function from_candid_ProductType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TarotService_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TarotService): TarotService {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isUrgent: boolean;
    name: string;
    description: string;
    category: _ServiceCategory;
    price: bigint;
    isVoiceNote: boolean;
}): {
    id: bigint;
    isUrgent: boolean;
    name: string;
    description: string;
    category: ServiceCategory;
    price: bigint;
    isVoiceNote: boolean;
} {
    return {
        id: value.id,
        isUrgent: value.isUrgent,
        name: value.name,
        description: value.description,
        category: from_candid_ServiceCategory_n15(_uploadFile, _downloadFile, value.category),
        price: value.price,
        isVoiceNote: value.isVoiceNote
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    careerMoneyLife: Array<_TarotService>;
    premiumExclusive: Array<_TarotService>;
    miniReadings: Array<_TarotService>;
    deepDetailed: Array<_TarotService>;
    loveRelationship: Array<_TarotService>;
}): {
    careerMoneyLife: Array<TarotService>;
    premiumExclusive: Array<TarotService>;
    miniReadings: Array<TarotService>;
    deepDetailed: Array<TarotService>;
    loveRelationship: Array<TarotService>;
} {
    return {
        careerMoneyLife: from_candid_vec_n12(_uploadFile, _downloadFile, value.careerMoneyLife),
        premiumExclusive: from_candid_vec_n12(_uploadFile, _downloadFile, value.premiumExclusive),
        miniReadings: from_candid_vec_n12(_uploadFile, _downloadFile, value.miniReadings),
        deepDetailed: from_candid_vec_n12(_uploadFile, _downloadFile, value.deepDetailed),
        loveRelationship: from_candid_vec_n12(_uploadFile, _downloadFile, value.loveRelationship)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    name: string;
    description: string;
    productType: _ProductType;
    imageUrl: string;
    price: bigint;
    isTrending: boolean;
}): {
    id: ProductId;
    name: string;
    description: string;
    productType: ProductType;
    imageUrl: string;
    price: bigint;
    isTrending: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        productType: from_candid_ProductType_n10(_uploadFile, _downloadFile, value.productType),
        imageUrl: value.imageUrl,
        price: value.price,
        isTrending: value.isTrending
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendulum: null;
} | {
    bracelet: null;
} | {
    crystal: null;
}): ProductType {
    return "pendulum" in value ? ProductType.pendulum : "bracelet" in value ? ProductType.bracelet : "crystal" in value ? ProductType.crystal : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    careerMoneyLife: null;
} | {
    premiumExclusive: null;
} | {
    miniReading: null;
} | {
    deepDetailed: null;
} | {
    loveRelationship: null;
}): ServiceCategory {
    return "careerMoneyLife" in value ? ServiceCategory.careerMoneyLife : "premiumExclusive" in value ? ServiceCategory.premiumExclusive : "miniReading" in value ? ServiceCategory.miniReading : "deepDetailed" in value ? ServiceCategory.deepDetailed : "loveRelationship" in value ? ServiceCategory.loveRelationship : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TarotService>): Array<TarotService> {
    return value.map((x)=>from_candid_TarotService_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ProductType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): {
    pendulum: null;
} | {
    bracelet: null;
} | {
    crystal: null;
} {
    return value == ProductType.pendulum ? {
        pendulum: null
    } : value == ProductType.bracelet ? {
        bracelet: null
    } : value == ProductType.crystal ? {
        crystal: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    careerMoneyLife: null;
} | {
    premiumExclusive: null;
} | {
    miniReading: null;
} | {
    deepDetailed: null;
} | {
    loveRelationship: null;
} {
    return value == ServiceCategory.careerMoneyLife ? {
        careerMoneyLife: null
    } : value == ServiceCategory.premiumExclusive ? {
        premiumExclusive: null
    } : value == ServiceCategory.miniReading ? {
        miniReading: null
    } : value == ServiceCategory.deepDetailed ? {
        deepDetailed: null
    } : value == ServiceCategory.loveRelationship ? {
        loveRelationship: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
