/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'status' : string,
  'dateOfBirth' : string,
  'createdAt' : bigint,
  'selectedServicePrice' : bigint,
  'fullName' : string,
  'email' : string,
  'selectedService' : string,
  'problemDescription' : string,
  'phone' : string,
}
export interface NewsletterSignupRecord {
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
}
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'productType' : ProductType,
  'imageUrl' : string,
  'price' : bigint,
  'isTrending' : boolean,
}
export type ProductId = string;
export type ProductType = { 'pendulum' : null } |
  { 'bracelet' : null } |
  { 'crystal' : null };
export type ServiceCategory = { 'careerMoneyLife' : null } |
  { 'premiumExclusive' : null } |
  { 'miniReading' : null } |
  { 'deepDetailed' : null } |
  { 'loveRelationship' : null };
export interface TarotService {
  'id' : bigint,
  'isUrgent' : boolean,
  'name' : string,
  'description' : string,
  'category' : ServiceCategory,
  'price' : bigint,
  'isVoiceNote' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [ProductId, string, string, string, ProductType, boolean],
    undefined
  >,
  'addTarotService' : ActorMethod<
    [string, string, bigint, ServiceCategory, boolean, boolean],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    undefined
  >,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteTarotService' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllTarotServices' : ActorMethod<[], Array<TarotService>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNewsletterSignUps' : ActorMethod<[], Array<NewsletterSignupRecord>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[ProductType], Array<Product>>,
  'getProductsByType' : ActorMethod<[ProductType], Array<Product>>,
  'getTarotService' : ActorMethod<[bigint], TarotService>,
  'getTarotServiceCatalog' : ActorMethod<
    [],
    {
      'careerMoneyLife' : Array<TarotService>,
      'premiumExclusive' : Array<TarotService>,
      'miniReadings' : Array<TarotService>,
      'deepDetailed' : Array<TarotService>,
      'loveRelationship' : Array<TarotService>,
    }
  >,
  'getTarotServicesByCategory' : ActorMethod<
    [ServiceCategory],
    Array<TarotService>
  >,
  'getTrendingProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'signupNewsletter' : ActorMethod<[string, string], string>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, string, ProductType, bigint, boolean],
    undefined
  >,
  'updateTarotService' : ActorMethod<
    [bigint, string, string, bigint, ServiceCategory, boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];