/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const ProductType = IDL.Variant({
  'pendulum' : IDL.Null,
  'bracelet' : IDL.Null,
  'crystal' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'careerMoneyLife' : IDL.Null,
  'premiumExclusive' : IDL.Null,
  'miniReading' : IDL.Null,
  'deepDetailed' : IDL.Null,
  'loveRelationship' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productType' : ProductType,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
  'isTrending' : IDL.Bool,
});
export const TarotService = IDL.Record({
  'id' : IDL.Nat,
  'isUrgent' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ServiceCategory,
  'price' : IDL.Nat,
  'isVoiceNote' : IDL.Bool,
});
export const Appointment = IDL.Record({
  'status' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'createdAt' : IDL.Int,
  'selectedServicePrice' : IDL.Nat,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'selectedService' : IDL.Text,
  'problemDescription' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Text, ProductType, IDL.Bool],
      [],
      [],
    ),
  'addTarotService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ServiceCategory, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteTarotService' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllTarotServices' : IDL.Func([], [IDL.Vec(TarotService)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductType],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByType' : IDL.Func([ProductType], [IDL.Vec(Product)], ['query']),
  'getTarotService' : IDL.Func([IDL.Nat], [TarotService], ['query']),
  'getTarotServiceCatalog' : IDL.Func(
      [],
      [
        IDL.Record({
          'careerMoneyLife' : IDL.Vec(TarotService),
          'premiumExclusive' : IDL.Vec(TarotService),
          'miniReadings' : IDL.Vec(TarotService),
          'deepDetailed' : IDL.Vec(TarotService),
          'loveRelationship' : IDL.Vec(TarotService),
        }),
      ],
      ['query'],
    ),
  'getTarotServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(TarotService)],
      ['query'],
    ),
  'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Text, ProductType, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateTarotService' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ServiceCategory,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const ProductType = IDL.Variant({
    'pendulum' : IDL.Null,
    'bracelet' : IDL.Null,
    'crystal' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'careerMoneyLife' : IDL.Null,
    'premiumExclusive' : IDL.Null,
    'miniReading' : IDL.Null,
    'deepDetailed' : IDL.Null,
    'loveRelationship' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productType' : ProductType,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  const TarotService = IDL.Record({
    'id' : IDL.Nat,
    'isUrgent' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ServiceCategory,
    'price' : IDL.Nat,
    'isVoiceNote' : IDL.Bool,
  });
  const Appointment = IDL.Record({
    'status' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'createdAt' : IDL.Int,
    'selectedServicePrice' : IDL.Nat,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'selectedService' : IDL.Text,
    'problemDescription' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Text, ProductType, IDL.Bool],
        [],
        [],
      ),
    'addTarotService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ServiceCategory, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteTarotService' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllTarotServices' : IDL.Func([], [IDL.Vec(TarotService)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductType],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByType' : IDL.Func(
        [ProductType],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getTarotService' : IDL.Func([IDL.Nat], [TarotService], ['query']),
    'getTarotServiceCatalog' : IDL.Func(
        [],
        [
          IDL.Record({
            'careerMoneyLife' : IDL.Vec(TarotService),
            'premiumExclusive' : IDL.Vec(TarotService),
            'miniReadings' : IDL.Vec(TarotService),
            'deepDetailed' : IDL.Vec(TarotService),
            'loveRelationship' : IDL.Vec(TarotService),
          }),
        ],
        ['query'],
      ),
    'getTarotServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(TarotService)],
        ['query'],
      ),
    'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ProductType,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateTarotService' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ServiceCategory,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };