/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'productType' : ProductType,
  'imageUrl' : string,
  'price' : bigint,
  'isTrending' : boolean,
}
export type ProductId = string;
export type ProductType = { 'pendulum' : null } |
  { 'bracelet' : null } |
  { 'crystal' : null };
export type ServiceCategory = { 'careerMoneyLife' : null } |
  { 'premiumExclusive' : null } |
  { 'miniReading' : null } |
  { 'deepDetailed' : null } |
  { 'loveRelationship' : null };
export interface TarotService {
  'id' : bigint,
  'isUrgent' : boolean,
  'name' : string,
  'description' : string,
  'category' : ServiceCategory,
  'price' : bigint,
  'isVoiceNote' : boolean,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [ProductId, string, string, string, ProductType, boolean],
    undefined
  >,
  'addTarotService' : ActorMethod<
    [string, string, bigint, ServiceCategory, boolean, boolean],
    undefined
  >,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteTarotService' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllTarotServices' : ActorMethod<[], Array<TarotService>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[ProductType], Array<Product>>,
  'getProductsByType' : ActorMethod<[ProductType], Array<Product>>,
  'getTarotService' : ActorMethod<[bigint], TarotService>,
  'getTarotServiceCatalog' : ActorMethod<
    [],
    {
      'careerMoneyLife' : Array<TarotService>,
      'premiumExclusive' : Array<TarotService>,
      'miniReadings' : Array<TarotService>,
      'deepDetailed' : Array<TarotService>,
      'loveRelationship' : Array<TarotService>,
    }
  >,
  'getTarotServicesByCategory' : ActorMethod<
    [ServiceCategory],
    Array<TarotService>
  >,
  'getTrendingProducts' : ActorMethod<[], Array<Product>>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, string, ProductType, bigint, boolean],
    undefined
  >,
  'updateTarotService' : ActorMethod<
    [bigint, string, string, bigint, ServiceCategory, boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];